# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f0c78f19e912161bcfadaf621af98064dbb93ed6a1be6804aef0b966cec30ef8edb848b79ee0c407dd9927ac91cee07deee9876484d1fe45b7c7cffcd70436

test:
  secret_key_base: 92f145f5f3c56f8d5da2810b0ba6ba5918d408bce954d7adf9875599e6a5d96581f0d4063fee27771318f113c89b1e5b6903441c6f0b02d12b08de5dbf22e03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
